---
# tasks file for ec2_setup
 - name: start an instance with a public ip
   amazon.aws.ec2_instance:
     name: "ec2_for_php"
     key_name: "formumbairegion"
     region: ap-south-1
     aws_access_key: "{{ec2_access_key}}"
     aws_secret_key: "{{ec2_secret_key}}"
     instance_type: t2.micro
     security_group: sg-0d250325757a82cb0
     network_interfaces:
       - assign_public_ip: true
     image_id: ami-053b12d3152c0cc71
     tags:
       Enviornment: Production
   register: ec2_info

 - name: debug to check the values
   debug:
     var: ec2_info

 - name: wait for port 22 to become available
   wait_for:
     host: "{{ ec2_info.instances[0].network_interfaces[0].association.public_ip }}"
     port: 22
     delay: 10
     timeout: 300

 - name: Copy public key to EC2 instance
   copy:
     src: /home/rohan/.ssh/id_rsa.pub
     dest: "/home/ubuntu/.ssh/authorized_keys"
     owner: ubuntu
     group: ubuntu
     mode: '0600'
   delegate_to: "{{ ec2_info.instances[0].network_interfaces[0].association.public_ip }}"
   remote_user: ubuntu
   become: true

