---
# tasks file for iamrolecreationall

- name: Create IAM role with specific policies and trust relationship
  amazon.aws.iam_role:
    name: MyCustomIAMRole
    assume_role_policy_document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": [
                "codedeploy.amazonaws.com",
                "ec2.amazonaws.com",
                "codedeploy.ap-south-1.amazonaws.com"
              ]
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    state: present
    description: "Role for CodeDeploy and EC2"
    managed_policies:
      - arn:aws:iam::aws:policy/AdministratorAccess
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      - arn:aws:iam::aws:policy/AWSCodeDeployDeployerAccess
      - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

